const express = require('express');
const router = express.Router();

const adminRouter = require('./admin');
const bookingRouter = require('./booking');
const cartRouter = require('./cart');
const cartItemRouter = require('./cart_item');
const countryRouter = require('./country');
const customerRouter = require('./customer');
const customerAddressRouter = require('./customer_address');
const customerCardRouter = require('./customer_card');
const deliveryMethodRouter = require('./delivery_method');
const discountRouter = require('./discount');
const districtRouter = require('./district');
const eventRouter = require('./event');
const eventTypeRouter = require('./event_type');
const flatRouter = require('./flat');
const genderRouter = require('./gender');
const humanCategoryRouter = require('./human_category');
const langRouter = require('./lang');
const paymentMethodRouter = require('./payment_method');
const regionRouter = require('./region');
const seatRouter = require('./seat');
const seatTypeRouter = require('./seat_type');
const sectorRouter = require('./sector');
const ticketRouter = require('./ticket');
const ticketStatusRouter = require('./ticket_status');
const ticketTypeRouter = require('./ticket_type');
const typeRouter = require('./types');
const venueRouter = require('./venue');
const venuePhotoRouter = require('./venue_photo');
const venueTypesRouter = require('./venue_types');

router.use('/admins', adminRouter);
router.use('/bookings', bookingRouter);
router.use('/carts', cartRouter);
router.use('/cart-items', cartItemRouter);
router.use('/countries', countryRouter);
router.use('/customers', customerRouter);
router.use('/customer-addresses', customerAddressRouter);
router.use('/customer-cards', customerCardRouter);
router.use('/delivery-methods', deliveryMethodRouter);
router.use('/discounts', discountRouter);
router.use('/districts', districtRouter);
router.use('/events', eventRouter);
router.use('/event-types', eventTypeRouter);
router.use('/flats', flatRouter);
router.use('/genders', genderRouter);
router.use('/human-categories', humanCategoryRouter);
router.use('/langs', langRouter);
router.use('/payment-methods', paymentMethodRouter);
router.use('/regions', regionRouter);
router.use('/seats', seatRouter);
router.use('/seat-types', seatTypeRouter);
router.use('/sectors', sectorRouter);
router.use('/tickets', ticketRouter);
router.use('/ticket-statuses', ticketStatusRouter);
router.use('/ticket-types', ticketTypeRouter);
router.use('/types', typeRouter);
router.use('/venues', venueRouter);
router.use('/venue-photos', venuePhotoRouter);
router.use('/venue-types', venueTypesRouter);

module.exports = router;